sudo: false
language: ruby
rvm:
  - 2.3.0
  - jruby-9.1.7.0
before_install:
  - wget https://github.com/nats-io/cnats/archive/master.zip
  - unzip master.zip
  - mv cnats-master cnats-1.5.0
  - mkdir -p cnats-1.5.0/build && cd cnats-1.5.0/build
  - cmake .. && make -j4
  - gem install bundler -v 1.14.3
  - gem update --system
addons:
  apt:
    packages:
      - build-essential
      - cmake
env:
  global:
    - NATS_LIB_PATH=$TRAVIS_BUILD_DIR/cnats-1.5.0/build/src
