sudo: false
language: ruby
rvm:
  - 2.3.0
  - jruby-9.1.7.0
before_install:
  - wget https://github.com/nats-io/cnats/archive/v1.5.0.tar.gz
  - tar -xvf v1.5.0.tar.gz
  - mkdir -p cnats-1.5.0/build && cd cnats-1.5.0/build
  - cmake .. -DCMAKE_SHARED_LINKER_FLAGS='-lrt' -DCMAKE_C_FLAGS='-lrt' && make -j4
  - gem install bundler -v 1.14.3
  - gem update --system
addons:
  apt:
    packages:
      - build-essential
      - cmake
env:
  global:
    - NATS_LIB_PATH=$TRAVIS_BUILD_DIR/cnats-1.5.0/build/src
